### ISSUE TITLE
Script Returning Errors for Destructive Op

### ISSUE THREAD

**Issue by A16D** [mrachinskiy/booltron#14]
Operating system: **Windows 11**
Blender version: **3.1.2**
Add-on version: **2.6.1**

🪲Error during execution of Destructive Bool ops
**Check Screenshot** ⬇️

![Booltron Error](https://user-images.githubusercontent.com/103478102/162878106-1abe6d7d-3228-45b7-adbb-32f9d47ec932.png)

**Comment by mrachinskiy** [comment]
Could you please provide steps to reproduce the issue?

**Comment by A16D** [comment]
Steps to Reproduce the Error - 

- Open Blender.exe
- Add a Cube Object
- Duplicate the Cube Object and Translate along x/y/z
- Now to do Boolean op Select the Cutter i.e. Dupilcate Cube Object and Traget mesh i.e. Cube object
- Use shortcut i.e CtrlB(custom) to open BoolTron Addon Panel Menu and Select "Difference" under "Destructive Mode" 
- Returns the Above screenshoted Error

**Comment by mrachinskiy** [comment]
Does it work if you use it from the Sidebar panel?

**Comment by mrachinskiy** [comment]
OK I reproduced it. Error appears only when menu called by hotkey, will investigate.

**Comment by mrachinskiy** [comment]
Thanks for the report! Fix will be available in the next release.

**Comment by A16D** [comment]
Thank You !
Loking frwd to the realese as I use it everday, almost !

Mai I ask What is the purpose of the Feature which creates a Thrid object called "Combined.obj.name" while executing aboolean operation, for example In above screenshot, when doing a difference boolean operation, the addon created  a third Object called Combined.obj.name set to Bounds view ?

**Comment by mrachinskiy** [comment]
It is much faster to boolean low poly objects together before doing boolean operation with high poly object.
And jewelry design it is most common case to boolean single high poly object (ring) with hundreds of small objects (prongs or cutters).
That is the purpose of combined object, it unifies all secondary objects into one.

With geometry nodes it is possible to do all that behind single GN modifier and skip creating separate object, but GN does not have Fast boolean solver. This forces me to use boolean modifier with separate combined object.
