### ISSUE TITLE
Please help to install BOOLTRON + Screenshot

### ISSUE THREAD

**Issue by AdamJeweler** [mrachinskiy/booltron#15]
Hello, please help me to install Booltron, when i activate the addon it doesn't work
![Capture d’écran 2022-04-25 213511](https://user-images.githubusercontent.com/103320950/165161404-69b85478-9423-45af-a150-0ad761997ca9.jpeg)

**IMPORTANT**
If error occurs on add-on installation or activation you probably trying to install add-on repository instead of release, check how to install guide (on the main page) for proper installation process.

**Please complete the following information**
Operating system:
Blender version:
Add-on version:

**Describe the bug**

**Screenshots**

**Comment by mrachinskiy** [comment]
If error occurs on add-on activation, it means you are trying to install add-on repository instead of release. Make sure you download add-on release using link provided in step one of installation guide.
