### ISSUE TITLE
Cutter meshes visible in renders with non-destructive operations

### ISSUE THREAD

**Issue by Rytelier** [mrachinskiy/booltron#17]
Blender version: 4.2
Add-on version: 2.9.0 Blender Extensions

When using non-destructive booleans, the cutter objects appear visible in the rendered view.
To fix, both the cutter and COMBINED meshes should have **Ray visibility Camera** and **Shadow** disabled in **Object -> Visibility** tab.

Preview view
![image](https://github.com/user-attachments/assets/82afc796-b41a-4b60-81f0-83dd66b45921)

Render view
![image](https://github.com/user-attachments/assets/7f549f99-5a36-4748-89c4-afa396766bd3)

**Comment by mrachinskiy** [comment]
Is this necessary? I always place secondary boolean objects in a separate collection and hide it.

**Comment by mrachinskiy** [comment]
New behavior will be available in next release.
