### ISSUE TITLE
Boolean coplanar faces

### ISSUE THREAD

**Issue by brothermechanic** [mrachinskiy/booltron#6]
Hello
Usefull addon!
I create a package for gentoo linux http://gpo.zugaina.org/media-blender/booltron !
This addon can't boolean coplanar faces (
For example this try to boolean 2 cudes.
[booltron-fail.zip](https://github.com/mrachinskiy/booltron/files/2352657/booltron-fail.zip)
Can you upgrade this addon for successfully complanal boolean?

**Comment by mrachinskiy** [comment]
Hi, you should use Carve solver, it handles simple cases of boolean coplanar geometry.
With BMesh solver use Correct Position setting, it will shift object position for a very small amount to avoid coplanar.

And thanks for gentoo package!

**Comment by brothermechanic** [comment]
Ok, but carve lib thrown to the frost...
Is the patch to get it back, do you know? (of cource i can use old releases)

**Comment by brothermechanic** [comment]
Hello
We created carve reversing patch
https://github.com/brothermechanic/cg/blob/master/local-patches/blender/CARVE-REVERSED.patch
