### ISSUE TITLE
Slice gives errors

### ISSUE THREAD

**Issue by Juris3D** [mrachinskiy/booltron#9]
Blender 2.90
trying new Booltron 1.5
with simple two cubes, destructive slice gives this error (scrrenshot)
![Booltron_Slice](https://user-images.githubusercontent.com/22710072/93188873-3100d480-f74a-11ea-9a68-274450326d1d.jpg)

**Comment by mrachinskiy** [comment]
Thanks for bug report the issue is fixed in 2.5.1 release.
